<a class="dotnet" data-id="50">Send GET REQUEST to dot net</a>
<br>
<br>
<a class="dotnetpostfamily" data-firstname="Annette" data-lastname="Munroe" data-typeofmember="Mother">Send POST REQUEST Update Family Table</a>

<script>
    $(".dotnet").click(function () {
        var num = $(this).attr("data-id");
        //alert(num);

        $.ajax({
            type: 'GET',
            url: 'http://localhost:53553/api/values',
//            data: { num: num },
            success: function (result) {
                //alert("It worked");
                console.log(result);
            }
        });
    });
    
    $(".dotnetpostfamily").click(function () {
        var family = {};
        family.First_Name = $(this).attr("data-firstname");
        family.Last_Name = $(this).attr("data-lastname");
        family.Type_Of_Member = $(this).attr("data-typeofmember");
        //alert(number);
        
        $.ajax({
            type: 'POST',
            url: 'http://localhost:53553/api/values',
            date: family,
            //data: JSON.stringify(number), // Need to use stringify and set the content type to json as im sending data through the body and not an object
            //contentType: "application/json; charset=utf-8",
            success: function (result) {
                console.log(result);
            }
        });
    });
</script>