<form action="/authentication/login" method="post">
    <fieldset>
        <label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="text" name="username" class="form-control" placeholder="Username" />
															<i class="icon-user"></i>
														</span>
        </label>

        <label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="text" name="password" class="form-control" placeholder="Password" />
															<i class="icon-user"></i>
														</span>
        </label>



        <div class="clearfix">

            <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
                <i class="icon-key"></i>
                Login
            </button>
        </div>

        <div class="space-4"></div>
    </fieldset>
</form>