<!DOCTYPE>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    
    <body ng-app="myApp" ng-controller="myCtrl">
        <div class="container">
            <form class="form-horizontal" id="regForm" method="post">
                <fieldset>
        
                  <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                  </div>
                  
                  <div class="form-group">
                    <label for="exampleSelect1">Choose Day</label>
                    <select class="form-control" name="choose_day" id="choose_day">
                      <option>Select Day</option>
                      <option>Monday</option>
                      <option>Tuesday</option>
                    </select>
                  </div>
                  
                  <div class="form-group">
                    <label for="comment">Comment</label>
                    <textarea class="form-control" name="comment" id="comment" rows="3"></textarea>
                  </div>
                  
<!--                  <fieldset class="form-group">
                    <legend>Checkboxes</legend>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" value="" checked="">
                        Option one is this and that—be sure to include why it's great
                      </label>
                    </div>
                    <div class="form-check disabled">
                      <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" value="" disabled="">
                        Option two is disabled
                      </label>
                    </div>
                  </fieldset>-->
                    
                  <fieldset class="form-group">
                    <legend>Payment Method</legend>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="payment_method" id="pay_paypal" value="paypal" checked="">
                        Paypall
                      </label>
                    </div>
                    <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="payment_method" id="pay_offline" value="offline">
                        Offline
                      </label>
                    </div>
                  </fieldset>
                    
                    <button type="submit" class="btn btn-primary" id="submit">Submit</button>
                  
                </fieldset>
              </form>
        </div>
    </body>
</html>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>

<script>
    
var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope) {
    $("#submit").click(function() {
        var data = $('#regForm').serialize();
//        console.log(datastring);
        
        $.ajax({
            type: 'POST',
            url: '/angularjs/processdata',
            data: data,
            success: function(result) {
                console.log(result);
            }
        })
    });
});

</script>

