<form action="/todo/index" method="post" enctype="multipart/form-data">
    <label for="task_for">Task For</label>
    <input id="task_for" type="text" name="task_for"><br>
    <label for="task_details">Task Details</label>
    <input id="task_details" type="text" name="task_details"><br>
    <label for="picture">Image Upload</label>
    <input type="file" name="picture" id="picture"><br>
    <input type="submit" value="Submit">
</form>