<form action="/s3/upload" method="post" enctype="multipart/form-data">
    <label for="picture">Image Upload</label>
    <input type="file" name="picture" id="picture"><br>
    <input type="submit" value="Submit">

</form><br><h1>Making a change to the master branch</h1><br>
<p>Make a change to master without knowing change made in branch</p>
<h3>ics branch</h3>

<p>Make update to mater</p>

<p>Make second update to master</p>

<p>Make change to branch before master</p>
