<!-- https://stripe.com/docs/payments/payment-intents/quickstart -->

<!-- Doesnt work ---- need to come back to it -->

<input type="radio" name='toolkit' class="toolkit" value="Single Toolkit" data-price='2500'> Single Toolkit<br>
<input type="radio" name='toolkit' class="toolkit" value="Half Module Toolkit" data-price='5000'> Half Module Toolkit<br>
<input type="radio" name='toolkit' class="toolkit" value="Full Module Toolkit" data-price='7500'> Full Module Toolkit<br><br>

<div id="payment-show" style="display: none;">
    <input id="cardholder-name" type="text">
    <!-- placeholder for Elements -->
    <div id="card-element"></div>
    <button id="card-button" data-secret="">
      Submit Payment
    </button>
</div>

<script>
    
$(".toolkit").click(function() {
    
    var item = $(this).val();
    var price = $(this).attr('data-price');
    console.log(item + ' is ' + price);
    
    $.ajax({
        type: 'POST',
        url: '/stripeelements/createpaymentintent',
        data: {price : price},
        success: function(response) {
            console.log(response);
            
            var client_secret = response['client_secret'];
            console.log(client_secret);
            
            $('#card-button').attr('data-secret', client_secret);
            $('#payment-show').css('display', 'block');
            
            runstripe();
            
        }
    });
    
});

function runstripe() {
    console.log("Stripe running");
    var stripe = Stripe('<?= STRIPE_PUBLIC_KEY; ?>');
    
    var elements = stripe.elements();
    var cardElement = elements.create('card');
    cardElement.mount('#card-element');
    
    $("#card-button").click(function() {
        var cardholderName = document.getElementById('cardholder-name');
        var cardButton = document.getElementById('card-button');
        var clientSecret = cardButton.dataset.secret;

        console.log(clientSecret);
    
        stripe.handleCardPayment(
            clientSecret, cardElement, {
              payment_method_data: {
                billing_details: {name: cardholderName.value}
              }
            }
          ).then(function(result) {
            if (result.error) {
              // Display error.message in your UI.
            } else {
              // The payment has succeeded. Display a success message.
            }
        });
    });
}

</script>

<script src="https://js.stripe.com/v3/"></script>
