<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href =  "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
    <title>Tables</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 fixed-height">
            <h2>Header</h2>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4 links">
        <a href="<?php echo $this->url(array('controller'=>'report',
                                        'action'=>'engagement'));?>">Show Table</a>
        <br>
        <a href="<?php echo $this->url(array('controller'=>'report',
                                        'action'=>'other'));?>">Other Page</a>
        <br>
        <a href="<?php echo $this->url(array('controller'=>'report',
                                        'action'=>'dateyear'));?>">Date Year Dropdown</a>
        </div>
        <div class="col-sm-12 col-md-8 col-lg-8">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
</body>
</html>