<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href =  "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>Tables</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 fixed-height links">
            <h2 class="title">DeclanServer</h2>
            <a href="<?php echo $this->url(array('module'=>'port','controller'=>'report',
                'action'=>'engagement'));?>">Show Table</a>
            <a href="<?php echo $this->url(array('module'=>'port','controller'=>'report',
                'action'=>'other'));?>">Other Page</a>
            <a href="<?php echo $this->url(array('module'=>'port','controller'=>'report',
                'action'=>'dateyear'));?>">Date Year Dropdown</a>
            <a href="<?php echo $this->url(array('module'=>'port','controller'=>'report',
                'action'=>'ajaxdata'));?>">Ajax Data Dropdown</a>
            <a href="<?php echo $this->url(array('module'=>'port','controller'=>'report',
                'action'=>'testpostman'));?>">Test Postman</a>
            <a href="<?php echo $this->url(array('module'=>'port','controller'=>'report',
                'action'=>'tickbox'));?>">Tickbox</a>
            <a href="<?php echo $this->url(array('module'=>'intranet','controller'=>'data',
                'action'=>'events'));?>">Intranet Events</a>
            <a href="<?php echo $this->url(array('module'=>'default','controller'=>'event',
                'action'=>'index'));?>">Events</a>
            <a href="<?php echo $this->url(array('module'=>'default','controller'=>'event',
                'action'=>'addmultibleregistrants'));?>">Add Registrants</a>
            <a href="<?php echo $this->url(array('module'=>'default','controller'=>'event',
                'action'=>'datatable'));?>">Data Table</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 content">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
</body>
</html>