<form action="/public/event/addmultibleregistrants" method="post" id="regform" >

    <select id="selectEvent" name="whatselected">

        <option>Choose an Event</option>

        <?php foreach ($this->listings as $listing):?>

            <option value="<?php echo $listing->id; ?>"><?php echo $listing->title; ?></option>

        <?php endforeach; ?>


    </select>

    <?php for($i = 0; $i < 2; $i++) : ?>
    <input   id="fn_<?php echo $i; ?>" type="text" name="first_name[<?php echo $i; ?>]" >
    <input   id="ln_<?php echo $i; ?>" type="text" name="last_name[<?php echo $i; ?>]" >
    <input   id="email_<?php echo $i; ?>" type="text" name="email[<?php echo $i; ?>]" >
    <br />
<?php endfor; ?>
    <input id="booked_by" type="text" name="booked_by" >
    <input type="submit" value = "Submit">

</form>

<table id="showRegistrants" class="table table-striped table-bordered table-hover display compact">
    <thead>
    <tr>
        <th>Event ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Booked By</th>
    </tr>

    </thead>
    <tbody>
    <?php foreach ($this->registrants as $reg):?>

        <tr>
            <td><?php echo $reg->event_id; ?></td>
            <td><?php echo $reg->first_name; ?></td>
            <td><?php echo $reg->last_name;?></td>
            <td><?php echo $reg->email; ?></td>
            <td><?php echo $reg->booking_first_name; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php print_r($_POST); ?>
