<!-- <table>
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Contact</th>
    <th>Photo</th>
    <th>&nbsp;</th>
</tr>
<!-- <?php $this->members = ""; ?> -->
<!-- <?php foreach($this->members as $result) : ?>
<tr>
    <td><?php echo $result["first_name"];?></td>
</tr>
<?php endforeach; ?>
</table> --> -->

<!-- <?php var_dump($this->members); ?>
<?php echo $this->members['first_name']; ?> -->

<?php if (count($this->members) > 0): ?>
<table>
  <thead>
    <tr>
      <th><?php echo implode('</th><th>', array_keys(current($this->members))); ?></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->members as $row): array_map('htmlentities', $row); ?>
    <tr>
      <td><?php echo implode('</td><td>', $row); ?></td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>
<?php endif; ?> 

<h4>There are : <?php echo count($this->members); ?> people in the table</h4>