<button type='button' class="buy-now" data-price='1000'>Half Toolkit</button>
<button type='button' class="buy-now" data-price='2000'>Full Toolkit</button>

<script>
    
$(".buy-now").click(function() {

var price = $(this).attr('data-price');

    $.ajax({
        type: 'POST',
        url: '/stripecheckout/chargeandcreate',
        data: {price : price},
        success: function(result) {
            console.log(result);
        }
    });
    
});

</script>

